version: "3"
services:
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    platform: linux/x86_64
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      # DB_HOST: db
      DB_USER: root
      # MYSQL_ROOT_PASSWORD:
    ports:
      - "3001:3000"
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/node_modules:/frontend/node_modules
    command: yarn run serve
    ports:
      - 81:8080
    depends_on:
      - backend
    stdin_open: true
    tty: true
    
volumes:
  mysql-data:
